apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels: 
    app: app0
spec:
  containers:
  - name: container-busybox
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
