apiVersion: v1
kind: Pod
metadata:
  name: second-pod
  labels: 
    app: app1
    environment: qa
    admin: aadi
spec:
  containers:
  - name: container-busybox
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
