apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubernetes.io/change-cause: kubectl set image deployment/nginx-2 nginix=nginx:1.7.9
      --record=true
  creationTimestamp: "2020-06-06T00:54:06Z"
  generation: 6
  labels:
    app: nginx-3
    ver: 1
  name: nginx-3
  namespace: default
  resourceVersion: "212621"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx-2
  uid: 392518a1-a790-11ea-9de6-06c8107f3782
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-3
	ver: 1
    spec:
      containers:
      - image: nginx:1.7.9
        imagePullPolicy: Always
        name: nginix
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-06-06T00:54:06Z"
    lastUpdateTime: "2020-06-06T01:09:54Z"
    message: ReplicaSet "nginx-2-dfcdd976b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-06-06T21:05:58Z"
    lastUpdateTime: "2020-06-06T21:05:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 6
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
